### ISSUE TITLE
Eclipse update blocked, jenkins repository not found

### ISSUE THREAD

**Issue by jkeruzec** [de-jcup/eclipse-jenkins-editor#90]
![image](https://user-images.githubusercontent.com/3499632/122871991-150d0d80-d330-11eb-8b31-663b5dfb658c.png)

**Comment by de-jcup** [comment]
the update site location has changed - with https://github.com/de-jcup/eclipse-jenkins-editor/issues/91 this will be changed inside the plugin feature.xml

in the mean while : Please got to Help->Eclipse marketplace and update (or install) the plugin manually over ui :
![image](https://user-images.githubusercontent.com/11644753/123438113-ad292200-d5d0-11eb-8a59-ef522002470f.png)

This will work - I did it same way.
Only automated updates via update sites inside feature.xml have problems - will be fixed in a later version 1.9.0

**Comment by de-jcup** [comment]
By the way:   This is because of the sundown of bintray - see https://github.com/de-jcup/eclipse-jenkins-editor/issues/91 (I was forced to move to another location). 

It does also influence another plugin in your screenshot (IMHO): mapstruct was /or is also hosted at bintray. And bintray  is - as mentioned before - no longer accessible.

If you have same problems with mapstruct, please visit the project page and look for a new update site location or try to update/reinstall from eclipse marketplace client as described before.

**Comment by de-jcup** [comment]
With 68e7ae1c76337722faeea6e3d996724327f9f065 this was already fixed in [Version 1.8..0](https://github.com/de-jcup/eclipse-jenkins-editor/releases/tag/v1.8.0) which is available eclipse marketplace. So closing this issue.

**Comment by jasonmenard** [comment]
For some reason it seems this issue is still occurring. Getting the same error again today. I tried installing from Market place and via URL and in both cases it fails with error: 

Unable to read repository at https://de-jcup.github.io/update-site-eclipse-jenkins-editor/update-site/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

![Jenkins-Editor-Plugin_Error](https://user-images.githubusercontent.com/87445711/125680272-8d631e6f-f654-4d94-a2a0-5b3057c3c98a.JPG)

Was anything changed since you close this issue?
Please let us know how we can workaround this since we use this plug in every day :)

**Comment by de-jcup** [comment]
## About server certificate problem
This seems to be an issue with the server certificate from github server and your used JDK. The server certificate is not accepted by your JRE or JDK which runs your eclipse instance. 

## Test by myself
I tried out on a fresh Eclipse 2021-06 via marketplace:

![image](https://user-images.githubusercontent.com/11644753/125955110-44fa7400-1062-4f59-95ca-8dd809a47c76.png)

installation worked well:
![image](https://user-images.githubusercontent.com/11644753/125955199-855a5de4-8b5d-4355-8ce0-ba8aaa244b2d.png)


## Suggestion
Please try out with a newer JDK /JRE version.

## Details
### About content.xml
The mentioned `content.xml` does not exist at https://github.com/de-jcup/update-site-eclipse-jenkins-editor/tree/main/update-site which is the origin for https://de-jcup.github.io/update-site-eclipse-jenkins-editor/update-site .

So https://de-jcup.github.io/update-site-eclipse-jenkins-editor/update-site/content.xml is not available but this is not the real problem, because e https://de-jcup.github.io/update-site-eclipse-jenkins-editor/update-site/content.jar is available and used by eclipse. So please don't be confused by the URL. The real problem is the unaccepted server certificate.

**Comment by de-jcup** [comment]
I just installed with eclipse 2021-12 from marketplace without any problems. So closing this
